language: ruby
dist: bionic
sudo: false
branches:
  only:
    - master
addons:
  postgresql: '10'
services:
  - mysql
cache:
  bundler: true
  directories:
    - /home/travis/.webdrivers/
import:
  - land-of-apps/land-of-apps:travis/ruby-imports.yml
before_install:
  - gem update bundler
bundler_args: --without development
before_script:
  - export RETRY_COUNT=3
  - bin/rake refinery:testing:dummy_app
script:
  - APPMAP=true bundle exec rspec
after_script:
  - env DEBUG=true ruby ./upload-appmaps tmp/appmap/*
env:
  - DB=postgresql
notifications:
  email: true
  webhooks:
    - https://webhooks.gitter.im/e/b5d48907cdc89864b874
rvm:
  - 2.6
