version: ~> 1.0
language: ruby
dist: bionic
sudo: false
addons:
  postgresql: '10'
cache:
  bundler: true
  directories:
    - /home/travis/.webdrivers/
import:
  - land-of-apps/land-of-apps:travis/ruby-imports.yml
script:
  - export RETRY_COUNT=3
  - bin/rake refinery:testing:dummy_app
  - APPMAP=true bundle exec rake
env:
  - DB=postgresql
rvm:
  - 2.6
