
version: ~> 1.0
language: ruby
cache: bundler
addons:
  postgresql: '10'
before_script:
  - export RETRY_COUNT=3
  - bin/rake refinery:testing:dummy_app
import:
  - land-of-apps/land-of-apps:travis/ruby-imports.yml
script:
  - APPMAP=true bundle exec rake
env:
  - DB=postgresql
rvm:
  - 2.6.6
sudo: false
