language: ruby
cache: bundler
before_install: gem install bundler
bundler_args: --without development
addons:
  postgresql: '10'
before_script:
  - export RETRY_COUNT=3
  - bin/rake refinery:testing:dummy_app
script:
  - APPMAP=true bundle exec rake
env:
  - DB=postgresql
rvm:
  - 2.6.6
sudo: false
